### ISSUE TITLE
AttributeError: 'DataCollector' object has no attribute 'agent_vars'

### ISSUE THREAD

**Issue by blockchain-trainer** [Havven/simulation#115]
Executing on Linux 18.04 

Right after install

```
yash@yash-Lenovo-G50-80:/media/yash/data/agent_based/simulation$ python3 run.py
No settings.ini file present, creating one with default settings.
Running cached data server...

Generating Balanced
  0%|                                                  | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    S: ModularServer = server.make_server()
  File "/media/yash/data/agent_based/simulation/core/server.py", line 213, in make_server
    server = CachedModularServer(settings, charts, "Havven Model (Alpha)")
  File "/media/yash/data/agent_based/simulation/visualization/cached_server.py", line 164, in __init__
    self.cached_data_handler = CachedDataHandler(settings)
  File "/media/yash/data/agent_based/simulation/visualization/cached_server.py", line 98, in __init__
    data = cache_handler.generate_new_caches(data)
  File "/media/yash/data/agent_based/simulation/core/cache_handler.py", line 188, in generate_new_caches
    element_data = element.render(havven_model)
  File "/media/yash/data/agent_based/simulation/visualization/modules/wealth_graphs.py", line 79, in render
    if len(data_collector.agent_vars["Agents"]) <= 1:
AttributeError: 'DataCollector' object has no attribute 'agent_vars'
```

**Comment by 0xdomrom** [comment]
This repo has not been touched in over three years. Issue is a result of the modules deprecating certain functionality. Either the modules should have fixed versions or code must be updated to prevent this
